# 📘 NumPy Basics in Python
This notebook covers the fundamental concepts and usage of NumPy.

## 1. Importing NumPy

In [1]:
import numpy as np

## 2. Creating Arrays

In [2]:
a = np.array([1, 2, 3])
print("1D array:", a)

b = np.array([[1, 2], [3, 4]])
print("2D array:\n", b)

1D array: [1 2 3]
2D array:
 [[1 2]
 [3 4]]


## 3. Array Attributes

In [3]:
print("Shape:", b.shape)
print("Dimensions:", b.ndim)
print("Data type:", b.dtype)

Shape: (2, 2)
Dimensions: 2
Data type: int64


## 4. Array Indexing and Slicing

In [4]:
print("First element:", a[0])
print("Second row:", b[1])
print("Element at (1,1):", b[1,1])

First element: 1
Second row: [3 4]
Element at (1,1): 4


## 5. Array Operations

In [5]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print("Addition:", x + y)
print("Multiplication:", x * y)
print("Dot product:", np.dot(x, y))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Dot product: 32


## 6. Useful NumPy Functions

In [6]:
print("Zeros:", np.zeros((2, 3)))
print("Ones:", np.ones((2, 3)))
print("Range:", np.arange(0, 10, 2))
print("Linspace:", np.linspace(0, 1, 5))

Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]
Range: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


## 7. Reshaping Arrays

In [7]:
arr = np.arange(6)
print("Original:", arr)
reshaped = arr.reshape((2, 3))
print("Reshaped to 2x3:\n", reshaped)

Original: [0 1 2 3 4 5]
Reshaped to 2x3:
 [[0 1 2]
 [3 4 5]]


## 8. Aggregation Functions

In [8]:
print("Sum:", np.sum(b))
print("Max:", np.max(b))
print("Mean:", np.mean(b))

Sum: 10
Max: 4
Mean: 2.5


## 9. Random Module

In [9]:
print("Random integers:", np.random.randint(0, 10, (2, 3)))
print("Random floats:", np.random.rand(2, 3))

Random integers: [[7 6 7]
 [0 1 4]]
Random floats: [[0.37453557 0.74845326 0.05561272]
 [0.20438351 0.19493933 0.540898  ]]


## 10. Boolean Masking and Filtering

In [10]:
data = np.array([10, 20, 30, 40])
mask = data > 25
print("Mask:", mask)
print("Filtered:", data[mask])

Mask: [False False  True  True]
Filtered: [30 40]
